name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Build
        run: dotnet build Peasmod/Peasmod.csproj --configuration Release

      - name: Upload Peasmod
        uses: actions/upload-artifact@v4
        with:
          name: Peasmod.dll
          path: Peasmod/bin/Release/net6.0/Peasmod.dll
